/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#acb6c5",
        "inverse-primary": "#785a00",
        "surface-container-low": "#181c21",
        "on-primary": "#3f2e00",
        "secondary": "#bec7d7",
        "on-background": "#e0e2ea",
        background: "#101419",
        "tertiary-fixed-dim": "#83cfff",
        "on-primary-container": "#604700",
        "inverse-surface": "#e0e2ea",
        "on-primary-fixed": "#251a00",
        "primary-fixed-dim": "#f7be1d",
        "on-tertiary-fixed": "#001e2e",
        "surface-tint": "#f7be1d",
        error: "#ffb4ab",
        "tertiary-container": "#60c5ff",
        "secondary-container": "#3e4755",
        "surface-bright": "#36393f",
        tertiary: "#adddff",
        "on-secondary-fixed": "#131c28",
        "on-tertiary-container": "#005072",
        surface: "#101419",
        "primary-fixed": "#ffdf9a",
        "secondary-fixed-dim": "#bec7d7",
        "on-tertiary-fixed-variant": "#004c6c",
        "outline-variant": "#4f4633",
        "surface-variant": "#31353b",
        "surface-container": "#1c2025",
        "inverse-on-surface": "#2d3136",
        "surface-dim": "#101419",
        "tertiary-fixed": "#c7e7ff",
        "on-secondary": "#28313d",
        "on-error": "#690005",
        outline: "#9b8f79",
        "on-primary-fixed-variant": "#5a4300",
        "surface-container-highest": "#31353b",
        "on-secondary-fixed-variant": "#3e4755",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#dae3f4",
        "surface-container-high": "#262a30",
        primary: "#ffd165",
        "surface-container-lowest": "#0a0e13",
        "on-surface-variant": "#d3c5ac",
        "error-container": "#93000a",
        "on-tertiary": "#00344c",
        "primary-container": "#eab308",
        "on-surface": "#e0e2ea",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        sm: "8px",
        "container-max": "1440px",
        lg: "24px",
        md: "16px",
        unit: "4px",
        xs: "4px",
        gutter: "20px",
        xl: "32px",
      },
      fontFamily: {
        h1: ["Inter", "sans-serif"],
        code: ["Inter", "monospace"],
        "label-caps": ["Inter", "sans-serif"],
        h3: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        h2: ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-base": ["Inter", "sans-serif"],
        "mono-label": ["Inter", "monospace"],
      },
      fontSize: {
        h1: ["30px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
        code: ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        h3: ["18px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        h2: ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}

